imageName: "localhost:5000/automate-all-the-things-docker-pi2"
bucketName: ""
backendFile: "terraformConfig.tf"
backendPath: "dev/s3/terraform.tfstate"
dockerHubCredential: "docker_hub"
awsCredential: "AWS_ACCESS_KEY"
slackToken: ""
slackChannel: "general-old"
successAction: "curl -X POST https://maker.ifttt.com/trigger/jenkins_success/with/key/geqAu4WK7xgLcr4md038_CrKCsXrRjZbJ9MsQBwPLg9"
failureAction: "curl -X POST https://maker.ifttt.com/trigger/jenkins_failure/with/key/geqAu4WK7xgLcr4md038_CrKCsXrRjZbJ9MsQBwPLg9"
